### ISSUE TITLE
Inline inputs

### ISSUE THREAD

**Issue by Maqsim** [StarterSquad/ngseed#28]
Would be cool add new Misc modifier `__inline` to user static predefined width of certain inputs such as input:date, input:time

``` scss
&.__inline {
  display: inline;
  width: auto;
}
```
